#ifndef ANDROIDTOOLS_GLOBAL_H
#define ANDROIDTOOLS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ANDROIDTOOLS_LIBRARY)
#  define ANDROIDTOOLSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ANDROIDTOOLSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ANDROIDTOOLS_GLOBAL_H
